import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { SideMenu } from "../shared/side_menu/side_menu";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Edumetrics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="w-full min-h-full h-full flex flex-col bg-background">
        <div className="flex h-full">
          <SideMenu />
          {children}
          {modal}
        </div>
      </body>
    </html>
  );
}
